LOG_MAX_SIZE=SUCCESS
LOG_MAX_FILES=SUCCESS
LOG_PATH=SUCCESS
LOG_FMT_PRESET=SUCCESS
LOG_FMT_OFFSET_DATE=SUCCESS
LOG_FMT_OFFSET_LABEL=SUCCESS
LOG_FMT_OFFSET_MESSAGE=SUCCESS
LOG_FMT_OFFSET_HOSTNAME=SUCCESS
LOG_FMT_OFFSET_SCRIPTNAME=SUCCESS
LOG_FMT_OFFSET_LINENO=SUCCESS
LOG_FMT_SYM_ENTRY=SUCCESS
LOG_FMT_SYM_TRACE_IN=SUCCESS
LOG_FMT_SYM_TRACE=SUCCESS
LOG_FMT_SYM_TRACE_OUT=SUCCESS
LOG_FMT_SYM_EXIT=SUCCESS
LOG_FMT_SYM_INFO=SUCCESS
LOG_FMT_SYM_SUCCESS=SUCCESS
LOG_FMT_SYM_WARNING=SUCCESS
LOG_FMT_SYM_ERROR=SUCCESS
LOG_FMT_SYM_DEBUG=SUCCESS
LOG_FMT_SYM_CUSTOM=SUCCESS
LOG_LEVEL_ANYTHING=SUCCESS
LOG_FORMAT_ANYTHING=SUCCESS

LOG_INVALID_OPT=FAIL
LOG_FORMAT_-ILLEGAL=FAIL
